"""Polaroid-style photographs of New York City pigeons generated by AI."""
from __future__ import annotations

import io
from base64 import b64decode
from pathlib import Path

import click
import openai
from PIL import Image
from rich import print
from wonderwords import RandomWord


@click.command()
@click.option("--output", "-o", default="./img/")
def cli(output):
    """Polaroid-style photographs of New York City pigeons generated by AI."""
    # Set our output directory
    output_dir = Path(output)

    # Get a list of all file stems in the output directory
    black_list = [p.stem for p in output_dir.glob("*.png")]
    adjective = get_random_adjective(black_list)

    # Get an image
    image = get_pigeon_polaroid(adjective)

    # Write it out to the filesystem
    # with the timestamp as the file name
    filename = f"{adjective}.png"
    filepath = output_dir / filename
    filepath.parent.mkdir(parents=True, exist_ok=True)
    print(f"Saving image to {filepath}...")
    image.save(filepath)


def get_random_adjective(black_list: list) -> str:
    """Get a random adjective.

    Args
    ----
    black_list (list)
        Words to exclude from selection

    Returns
    -------
    A string word
    """
    # Get a random adjective
    r = RandomWord()
    while True:
        adjective = r.word(include_parts_of_speech=["adjectives"])
        if adjective not in black_list:
            break
    return adjective


def get_pigeon_polaroid(adjective: str) -> Image:
    """Generate a Polaroid-style photograph of a pigeon in Manhattan."""
    print(f"Generating image for '{adjective}'")

    # Connect to OpenAI
    client = openai.OpenAI()

    # Prepare our prompt
    prompt = f"""A full-bleed, color image of a pigeon in New York City. The pigeon should dominate the foreground, its details captured meticulously. There should be no visible text. Realistic photography. The pigeon should appear {adjective}."""

    # Request an image from the API
    response = client.images.generate(
        model="dall-e-3",
        prompt=prompt,
        size="1024x1024",
        quality="hd",
        style="natural",
        n=1,
        response_format="b64_json",
    )

    # Write to an in-memory PIL object
    data = response.data[0].b64_json
    assert isinstance(data, str)
    bytes = b64decode(data)
    image = Image.open(io.BytesIO(bytes))

    # Return that object
    return image


if __name__ == "__main__":
    cli()
