"""Polaroid-style photographs of New York City pigeons generated by AI."""
from __future__ import annotations

import io
from base64 import b64decode
from datetime import datetime
from pathlib import Path

import click
import openai
from PIL import Image
from rich import print


@click.command()
@click.option("--output", "-o", type=Path, default=".")
def cli(output):
    """Polaroid-style photographs of New York City pigeons generated by AI."""
    # Get an image
    image = get_pigeon_polaroid()

    # Write it out to the filesystem
    # with the timestamp as the file name
    filename = f"{datetime.now()}.png"
    filepath = output / filename
    filepath.parent.mkdir(parents=True, exist_ok=True)
    print(f"Saving image to {filepath}...")
    image.save(filepath)


def get_pigeon_polaroid() -> Image:
    """Generate a Polaroid-style photograph of a pigeon in Manhattan."""
    print("Generating image...")

    # Connect to OpenAI
    client = openai.OpenAI()

    # Prepare our prompt
    prompt = """A close-up image that captures the essence of a pigeon in Manhattan. The image should evoke feelings from the 1970s and underground amateur photography, with the nostalgic charm similar to that of Polaroids. There should be colors but they should be washed out in the style of instant cameras like the Polaroid 635 Supercolor and the Fujifilm Instax. The city's skyline or other New York City landmarks like Central Park, the Hudson River, the Statue of Liberty, the New York Public Library, the Brooklyn Bridge, the Guggenheim, Times Square, Chinatown, Tribeca, the Upper West Side or Broadway can be subtly hinted at in the background, infusing subtle urban elements into the frame. The pigeon should dominate the foreground, its details captured meticulously. The image should fill the entire space with no frame and not border around it."""

    # Request an image from the API
    response = client.images.generate(
        model="dall-e-3",
        prompt=prompt,
        size="1024x1024",
        quality="hd",
        style="vivid",
        n=1,
        response_format="b64_json",
    )
    print("...image generated.")

    # Write to an in-memory PIL object
    bytes = b64decode(response.data[0].b64_json)
    image = Image.open(io.BytesIO(bytes))

    # Return that object
    return image


if __name__ == "__main__":
    cli()
