name: Extract, transform and load

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0,12 * * *'

permissions:
  contents: write

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        shell: bash

      - id: install-python-dependencies
        name: Install Python dependencies
        run: pipenv sync
        shell: bash

      - name: Generate image
        run: pipenv run python -m src.cli
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MASTODON_CLIENT_KEY: ${{ secrets.MASTODON_CLIENT_KEY }}
          MASTODON_CLIENT_SECRET: ${{ secrets.MASTODON_CLIENT_SECRET }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
